import { SET_COOKIE_PRIORITY_MEDIUM } from "./SET_COOKIE_PRIORITY.mjs";
import { SET_COOKIE_SAME_SITE_LAX } from "./SET_COOKIE_SAME_SITE.mjs";

export const SET_COOKIE_OPTION_DOMAIN = "Domain";

export const SET_COOKIE_OPTION_EXPIRES = "Expires";

export const SET_COOKIE_OPTION_HTTP_ONLY = "HttpOnly";

export const SET_COOKIE_OPTION_MAX_AGE = "Max-Age";

export const SET_COOKIE_OPTION_PATH = "Path";

export const SET_COOKIE_OPTION_PRIORITY = "Priority";

export const SET_COOKIE_OPTION_SAME_SITE = "SameSite";

export const SET_COOKIE_OPTION_SECURE = "Secure";

export const SET_COOKIE_OPTION_DEFAULT_HTTP_ONLY = true;

export const SET_COOKIE_OPTION_DEFAULT_MAX_AGE = 60 * 60 * 24 * 7;

export const SET_COOKIE_OPTION_DEFAULT_PATH = "/";

export const SET_COOKIE_OPTION_DEFAULT_PRIORITY = SET_COOKIE_PRIORITY_MEDIUM;

export const SET_COOKIE_OPTION_DEFAULT_SAME_SITE = SET_COOKIE_SAME_SITE_LAX;

export const SET_COOKIE_OPTION_DEFAULT_SECURE = true;

export const SET_COOKIE_OPTION_MAX_AGE_SESSION = 0;
