import { DEFAULT_PORT_HTTP, DEFAULT_PORT_HTTPS } from "./DEFAULT_PORT.mjs";
import { PROTOCOL_HTTP, PROTOCOL_HTTPS } from "./PROTOCOL.mjs";

export const PROTOCOL_DEFAULT_PORT = Object.freeze({
    [PROTOCOL_HTTPS]: DEFAULT_PORT_HTTPS,
    [PROTOCOL_HTTP]: DEFAULT_PORT_HTTP
});
