import { STATUS_302 } from "../Status/STATUS.mjs";

export const HTTP_SERVER_DEFAULT_DEVELOPMENT_MODE = false;

export const HTTP_SERVER_DEFAULT_LISTEN_HTTPS_PORT = 8_443;

export const HTTP_SERVER_DEFAULT_LISTEN_HTTP_PORT = 8_080;

export const HTTP_SERVER_DEFAULT_NO_POWERED_BY = true;

export const HTTP_SERVER_DEFAULT_NO_REFERRER = true;

export const HTTP_SERVER_DEFAULT_REDIRECT_HTTP_TO_HTTPS = true;

export const HTTP_SERVER_DEFAULT_REDIRECT_HTTP_TO_HTTPS_PORT = 443;

export const HTTP_SERVER_DEFAULT_REDIRECT_HTTP_TO_HTTPS_STATUS_CODE = STATUS_302;

export const HTTP_SERVER_LISTEN_HTTPS_PORT_DISABLED = 0;

export const HTTP_SERVER_LISTEN_HTTP_PORT_DISABLED = 0;
